travel_list=['Togo', 'Algeria', 'South Africa','Morocco','Japan']
print(travel_list)
print("sorting the location list")
print(sorted(travel_list))
print(travel_list)
print("This is the reverse sorted list")
print(sorted(travel_list, reverse=True))
print(travel_list)
travel_list.reverse()
print(travel_list)
travel_list.reverse()
print(travel_list)
travel_list.sort()
print(travel_list)
travel_list.sort(reverse=True)
print(travel_list)